# Trigger the workflow on push or pull request
on: [workflow_dispatch]
jobs:
  test_runner:
    name: ASAP test CTX pipeline
    needs: [cache_isis_env]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Get ISIS Conda environment from cache
        uses: actions/cache@v2
        with:
          path: "isis-env.tar.gz"
          key: isis-env-${{ runner.os }}-${{ env.ISIS_CACHE_NUMBER }}-${{ hashFiles('isis.yml') }}
      - name: Unpack ISIS Conda environment
        run: |
          mkdir -p $CONDA/envs/isis_for_asp
          tar -xzf "isis-env.tar.gz" -C $CONDA/envs/isis_for_asp
          ls $CONDA/envs/isis_for_asp
      - name: download and extract ASP tarball to tmp
        run: |
          mkdir /tmp/sp
          wget -c https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/2.7.0/StereoPipeline-2.7.0-2020-07-29-x86_64-Linux.tar.bz2 -O /tmp/sp.tar.bz2 --progress=dot:giga
          tar -xf /tmp/sp.tar.bz2 -C /tmp/sp --strip-components 1
          ls /tmp/sp
      - name: setup asap conda env
        uses: conda-incubator/setup-miniconda@v2.1.0
        with:
          mamba-version: "*"
          use-mamba: true
          activate-environment: asap
          environment-file: asap.yml
          python-version: 3.8
          channels: conda-forge,defaults
          use-only-tar-bz2: true
      - name: add ASP and ISIS to PATH of asap conda
        run: |
          conda env config vars set ISISROOT=$CONDA/envs/isis_for_asp
          conda env config vars set ISISDATA=$CONDA/envs/isis_for_asp/data
          conda env config vars set ISISTESTDATA=$CONDA/envs/isis_for_asp/testdata
          conda env config vars set PATH=$PATH:/tmp/sp/bin:$CONDA/envs/isis_for_asp/bin
      - name: install asap
        run: pip install -e .
      - name: conda info for asap
        run: |
          echo $PATH
          conda env config vars list
          conda info
          conda list
      - name: check isis shared libraries
        run: |
          ldd `which qview`
      - name: test for asap
        run: asap
      - name: asap step 1
        timeout-minutes: 5
        run: asap ctx step-1 B03_010644_1889_XN_08N001W P02_001902_1889_XI_08N001W
      - name: look before you leap
        run: |
          ls ./* -lahtr
          env | grep ISIS
          pwd
      - name: asap step 2
        timeout-minutes: 1
        run: asap ctx step-2
      - name: asap stereo quality report 
        run: |
          ls
          asap common get_stereo_quality_report ./B03_010644_1889_XN_08N001W.lev1eo.cub ./P02_001902_1889_XI_08N001W.lev1eo.cub
          ls
      - name: asap 4 & rescale images for test
        run: |
          asap ctx step-3
          asap common rescale_and_overwrite 8 
      - name: asap step 4
        run:  asap ctx step-4
      - name: asap step 5 (and get stereo conf files)
        run:  |
          wget https://raw.githubusercontent.com/NeoGeographyToolkit/StereoPipeline/master/examples/CTX/stereo.nonmap
          wget https://raw.githubusercontent.com/NeoGeographyToolkit/StereoPipeline/master/examples/CTX/stereo.map
          asap ctx step-5 ./stereo.nonmap
      - name: asap step 6
        run:  asap ctx step-6 ./stereo.nonmap
      - name: asap step 7-8
        run: |
          asap ctx step-7 --mpp 240 --dem_hole_fill_len 50
          asap ctx step-8
      - name: asap 1st round previews
        run: |
          ls -lahtr $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/
          gdal_translate -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba-GoodPixelMap.tif ./good_pixel_map_1.png
          ls -lahtr $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/dem/
          gdal_translate -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/dem/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba_240_0-DEM-hillshade.tif ./hillshade_1.png
      - name: Archive First Round Previews
        uses: actions/upload-artifact@v2
        with:
          name: first-round
          path: |
            good_pixel_map_1.png
            hillshade_1.png
      - name: asap step 9
        run:  asap ctx step-9 --refdem $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/dem/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba_240_0-DEM.tif --mpp 48
      - name: asap step 10-11
        run: |
          asap ctx step-10 --refdem $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/dem/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba_240_0-DEM.tif ./stereo.map
          asap ctx step-11 --refdem $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_ba/dem/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba_240_0-DEM.tif ./stereo.map
          asap ctx step-7 --mpp 144 --run results_map_ba
          asap ctx step-8 --run results_map_ba
      - name: asap step 12
        run:  asap ctx step-12 None
      - name: asap 2nd round previews
        run: |
          gdal_translate -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_map_ba/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba-GoodPixelMap.tif ./good_pixel_map_2.png
          gdal_translate -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_map_ba/dem/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_ba_144_0-DEM-hillshade.tif ./hillshade_2.png
      - name: Archive 2nd Round Previews
        uses: actions/upload-artifact@v2
        with:
          name: second-round
          path: |
            good_pixel_map_2.png
            hillshade_2.png
      - name: list contents of results_map_ba/dem
        run: ls $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_map_ba/dem/ -lahtr
      - name: asap step 13-17
        timeout-minutes: 2
        run: |
          asap ctx step-13 --highest_accuracy False --max-num-reference-points 100000 --max-num-source-points 10000
          asap ctx step-14 --mpp 144
          asap ctx step-15
          asap ctx step_8 --run results_map_ba --output_folder dem_align
          asap ctx step_14 --mpp 48 --just_ortho True
      - name: asap final previews
        run: |
          gdal_translate -ot Byte -scale 0 1 -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_map_ba/dem_align/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_map_ba_align_48_0-DRG.tif ./vis_f.png
          gdal_translate -of PNG $(pwd)/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W/results_map_ba/dem_align/B03_010644_1889_XN_08N001W_P02_001902_1889_XI_08N001W_map_ba_align_144_0-DEM-hillshade.tif ./hillshade_f.png
      - name: Archive Final Previews
        uses: actions/upload-artifact@v2
        with:
          name: final
          path: |
            hillshade_f.png
            vis_f.png
