# Trigger the workflow on push or pull request
on: [workflow_dispatch]
jobs:
  test_runner:
    name: asap test 
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          mamba-version: "*"
          activate-environment: asp
          environment-file: asp.yml
          python-version: 3.6
          channels: nasa-ames-stereo-pipeline,usgs-astrogeology,conda-forge,defaults
          channel-priority: true
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: isis3 path inits
        shell: bash -l {0}
        run: python $CONDA_PREFIX/scripts/isis3VarInit.py
      - name: install asap
        shell: bash -l {0}
        run: pip install -e .
      - name: conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: test for asap
        shell: bash -l {0}
        run: asap
      - name: asap step 1
        shell: bash -l {0}
        run: asap ctx step-one B03_010644_1889_XN_08N001W P02_001902_1889_XI_08N001W
      - name: asap step 2
        shell: bash -l {0}
        run: asap ctx step-two
      - name: asap rescale images for test
        shell: bash -l {0}
        run:  asap common rescale_and_overwrite 8
      - name: asap step 3
        shell: bash -l {0}
        run:  asap ctx step-three
      - name: asap step 4
        shell: bash -l {0}
        run:  asap ctx step-four