# Trigger the workflow on push or pull request
on: [workflow_dispatch]
jobs:
  test_runner:
    name: ASAP test Notebook CTX pipeline
    needs: [cache_isis_env]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Get ISIS Conda environment from cache
        uses: actions/cache@v2
        with:
          path: "isis-env.tar.gz"
          key: isis-env-${{ runner.os }}-${{ env.ISIS_CACHE_NUMBER }}-${{ hashFiles('isis.yml') }}
      - name: Unpack ISIS Conda environment
        run: |
          mkdir -p $CONDA/envs/isis_for_asp
          tar -xzf "isis-env.tar.gz" -C $CONDA/envs/isis_for_asp
          ls $CONDA/envs/isis_for_asp
      - name: download and extract ASP tarball to tmp
        run: |
          mkdir /tmp/sp
          wget -c https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/2.7.0/StereoPipeline-2.7.0-2020-07-29-x86_64-Linux.tar.bz2 -O /tmp/sp.tar.bz2 --progress=dot:giga
          tar -xf /tmp/sp.tar.bz2 -C /tmp/sp --strip-components 1
          ls /tmp/sp
      - name: setup asap conda env
        uses: conda-incubator/setup-miniconda@v2.1.0
        with:
          mamba-version: "*"
          use-mamba: true
          activate-environment: asap
          environment-file: asap.yml
          python-version: 3.8
          channels: conda-forge,defaults
          use-only-tar-bz2: true
      - name: add ASP and ISIS to PATH of asap conda
        run: |
          conda env config vars set ISISROOT=$CONDA/envs/isis_for_asp
          conda env config vars set ISISDATA=$CONDA/envs/isis_for_asp/data
          conda env config vars set ISISTESTDATA=$CONDA/envs/isis_for_asp/testdata
          conda env config vars set PATH=$PATH:/tmp/sp/bin:$CONDA/envs/isis_for_asp/bin
      - name: install asap
        run: pip install -e .
      - name: conda info for asap
        run: |
          echo $PATH
          conda env config vars list
          conda info
          conda list
      - name: check isis shared libraries
        run: |
          ldd `which qview`
      - name: test for asap
        run: asap
      - name: download stereo parameter files
        run:  |
          wget https://raw.githubusercontent.com/NeoGeographyToolkit/StereoPipeline/master/examples/CTX/stereo.nonmap
          wget https://raw.githubusercontent.com/NeoGeographyToolkit/StereoPipeline/master/examples/CTX/stereo.map
      - name: asap notebook run
        timeout-minutes: 30
        run: |
          asap ctx notebook_pipeline_make_dem B03_010644_1889_XN_08N001W P02_001902_1889_XI_08N001W ./stereo.nonmap --config2 ./stereo.map --downsample 8 --img_gsd 48 --dem_gsd 144 --step_kwargs '{"step_13": "--highest_accuracy False --max-num-reference-points 100000 --max-num-source-points 10000"}'
      - name: ls directories to see what was made
        continue-on-error: true
        if: always()
        run:
          ls ./ -lahtr   
          ls ./*/*/* -lahtr  
      - name: Archive Final Notebook from Papermill
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: final
          path: |
            *.log
            *.ipynb
