# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  test_runner:
    name: Ubuntu 
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ hashFiles('asp.yml') }}
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2.1.0
        with:
          mamba-version: "*"
          activate-environment: asp
          environment-file: asp.yml
          python-version: 3.6
          channels: nasa-ames-stereo-pipeline,usgs-astrogeology,conda-forge,defaults
          channel-priority: strict
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: install asap
        run: pip install -e .
      - name: conda info
        run: |
          conda info
          conda list
      - name: check isis shared libraries
        run: |
          ldd `which qview`
      - name: test for asap
        run: |
          asap
          asap ctx
          asap hirise
          asap common
