# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  test_runner:
    name: Ubuntu
    needs: [cache_isis_env]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Get ISIS Conda environment from cache
        uses: actions/cache@v2
        with:
          path: "isis-env.tar.gz"
          key: isis-env-${{ runner.os }}-${{ env.ISIS_CACHE_NUMBER }}-${{ hashFiles('isis.yml') }}
      - name: Unpack ISIS Conda environment
        run: |
          mkdir -p $CONDA/envs/isis_for_asp
          tar -xzf "isis-env.tar.gz" -C $CONDA/envs/isis_for_asp
          ls $CONDA/envs/isis_for_asp
      - name: rsync base kernels
      - name: download and extract ASP tarball to tmp
        run: |
          mkdir /tmp/sp
          wget -c https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/2.7.0/StereoPipeline-2.7.0-2020-07-29-x86_64-Linux.tar.bz2 -O /tmp/sp.tar.bz2 --progress=dot:giga
          tar -xf /tmp/sp.tar.bz2 -C /tmp/sp --strip-components 1
          ls /tmp/sp
      - name: setup asap conda env
        uses: conda-incubator/setup-miniconda@v2.1.0
        with:
          mamba-version: "*"
          use-mamba: true
          activate-environment: asap
          environment-file: asap.yml
          python-version: 3.8
          channels: conda-forge,defaults
          use-only-tar-bz2: true
      - name: add ASP and ISIS to PATH of asap conda
        run: |
          conda env config vars set ISISROOT=$CONDA/envs/isis_for_asp
          conda env config vars set ISISDATA=$CONDA/envs/isis_for_asp/data
          conda env config vars set ISISTESTDATA=$CONDA/envs/isis_for_asp/testdata
          conda env config vars set PATH=$PATH:/tmp/sp/bin:$CONDA/envs/isis_for_asp/bin
      - name: install asap
        run: pip install -e .
      - name: conda info
        run: |
          echo $PATH
          conda env config vars list
          conda info
          conda list
      - name: check isis shared libraries
        run: |
          ldd `which qview`
      - name: test for asap
        run: |
          asap
          asap ctx
          asap hirise
          asap common
      - name: Test readme rendering
        run: |
          python -m readme_renderer README.rst
