# Trigger the workflow on push or pull request
on: [push, pull_request]
env:
  # Increase this value to reset cache
  ISIS_CACHE_NUMBER: 3
  ASAP_CACHE_NUMBER: 2
  ASP_CACHE_NUMBER: 1
jobs:
  cache_asp:
    name: Cache ASP distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache ASP tarball
        id: cache-asap
        uses: actions/cache@v2
        with:
          path: "/tmp/sp.tar.bz2"
          key: asp-env-${{ runner.os }}-${{ env.ASP_CACHE_NUMBER }}-${{ hashFiles('asap.yml') }}
      - name: Download ASP tarball to tmp
        run: |
          wget -c https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/3.1.0/StereoPipeline-3.1.0-2022-05-18-x86_64-Linux.tar.bz2 -O /tmp/sp.tar.bz2 --progress=dot:giga
          ls /tmp/sp.tar.bz2
  cache_isis_env:
    name: Cache ISIS conda environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache ISIS conda env
        id: cache-isis
        uses: actions/cache@v2
        with:
          path: "isis-env.tar.gz"
          key: isis-env-${{ runner.os }}-${{ env.ISIS_CACHE_NUMBER }}-${{ hashFiles('isis.yml') }}
      - name: setup isis conda env
        if: steps.cache-isis.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          use-mamba: false
          activate-environment: isis_for_asp
          environment-file: isis.yml
          auto-update-conda: true
          use-only-tar-bz2: true
          clean-patched-environment-file: false
      - name: conda info for isis
        if: steps.cache-isis.outputs.cache-hit != 'true'
        run: |
          echo $PATH
          conda env config vars list
          conda info
          conda list
          ldd `which qview`
      - name: rsync base kernels
        if: steps.cache-isis.outputs.cache-hit != 'true'
        run: |
          rsync -azv --exclude='kernels' --exclude "dems" --exclude "testData" --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/base $CONDA/envs/isis_for_asp/data/
          rsync -azv --include '*/' --include "*.db"  --exclude "*"  --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/base/ $CONDA/envs/isis_for_asp/data/base
          mkdir -p $CONDA/envs/isis_for_asp/data/base/kernels/spk/
          mkdir -p $CONDA/envs/isis_for_asp/data/base/kernels/lsk/
          mkdir -p $CONDA/envs/isis_for_asp/data/base/kernels/pck/
          mkdir -p $CONDA/envs/isis_for_asp/data/base/dems/
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/de430.bsp -O $CONDA/envs/isis_for_asp/data/base/kernels/spk/de430.bsp
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mar097.bsp -O $CONDA/envs/isis_for_asp/data/base/kernels/spk/mar097.bsp
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/naif0012.tls -O $CONDA/envs/isis_for_asp/data/base/kernels/lsk/naif0012.tls
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/pck00009.tpc -O $CONDA/envs/isis_for_asp/data/base/kernels/pck/pck00009.tpc
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/molaMarsPlanetaryRadius0005_cropped.cub -O $CONDA/envs/isis_for_asp/data/base/dems/molaMarsPlanetaryRadius0005.cub
      - name: rsync mro data
        if: steps.cache-isis.outputs.cache-hit != 'true'
        run: |
          rsync -azv --exclude='kernels' --exclude "testData" --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/mro $CONDA/envs/isis_for_asp/data/
          rsync -azv --include '*/' --include "*.db"  --exclude "*"  --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/mro/ $CONDA/envs/isis_for_asp/data/mro
          mkdir -p $CONDA/envs/isis_for_asp/data/mro/kernels/spk/
          mkdir -p $CONDA/envs/isis_for_asp/data/mro/kernels/sclk/
          mkdir -p $CONDA/envs/isis_for_asp/data/mro/kernels/ck/
          mkdir -p $CONDA/envs/isis_for_asp/data/mro/kernels/iak/
          mkdir -p $CONDA/envs/isis_for_asp/data/mro/kernels/fk/
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mro_v15.tf -O $CONDA/envs/isis_for_asp/data/mro/kernels/fk/mro_v15.tf
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/MRO_SCLKSCET.00090.65536.tsc -O $CONDA/envs/isis_for_asp/data/mro/kernels/sclk/MRO_SCLKSCET.00090.65536.tsc
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mroctxAddendum005.ti -O $CONDA/envs/isis_for_asp/data/mro/kernels/iak/mroctxAddendum005.ti
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mro_sc_psp_061219_061225_subset.bc -O $CONDA/envs/isis_for_asp/data/mro/kernels/ck/mro_sc_psp_061219_061225.bc
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mro_sc_psp_081028_081103_subset.bc -O $CONDA/envs/isis_for_asp/data/mro/kernels/ck/mro_sc_psp_081028_081103.bc
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mro_psp1_ssd_mro110c_subset.bsp -O $CONDA/envs/isis_for_asp/data/mro/kernels/spk/mro_psp1_ssd_mro110c.bsp
          wget https://github.com/AndrewAnnex/asap_stereo_test_data/raw/master/mro_psp9_ssd_mro110c_subset.bsp -O $CONDA/envs/isis_for_asp/data/mro/kernels/spk/mro_psp9_ssd_mro110c.bsp
      - name: pack isis conda env
        if: steps.cache-isis.outputs.cache-hit != 'true'
        run: |
          tar -cvzf isis-env.tar.gz $CONDA/envs/isis_for_asp
          pwd
          ls -lahtr

  cache_asap_env:
    name: Cache ASAP conda environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache ASAP conda env
        id: cache-asap
        uses: actions/cache@v2
        with:
          path: "asap-env.tar.gz"
          key: asap-env-${{ runner.os }}-${{ env.ASAP_CACHE_NUMBER }}-${{ hashFiles('asap.yml') }}
      - name: setup asap conda env
        if: steps.cache-asap.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2.1.0
        with:
          mamba-version: "*"
          use-mamba: true
          activate-environment: asap
          environment-file: asap.yml
          python-version: 3.9
          channels: conda-forge,defaults
          use-only-tar-bz2: true
      - name: add ASP and ISIS to PATH of asap conda
        if: steps.cache-asap.outputs.cache-hit != 'true'
        run: |
          conda env config vars set ISISROOT=$CONDA/envs/isis_for_asp
          conda env config vars set ISISDATA=$CONDA/envs/isis_for_asp/data
          conda env config vars set ISISTESTDATA=$CONDA/envs/isis_for_asp/testdata
          conda env config vars set PATH=$PATH:/tmp/sp/bin:$CONDA/envs/isis_for_asp/bin
      - name: conda info
        if: steps.cache-asap.outputs.cache-hit != 'true'
        run: |
          echo $PATH
          conda env config vars list
          conda info
          conda list
      - name: pack asap conda env
        if: steps.cache-asap.outputs.cache-hit != 'true'
        run: |
          tar -cvzf asap-env.tar.gz $CONDA/envs/asap
          pwd
          ls -lahtr

  test_basic:
    name: Basic ASAP Tests
    needs: [cache_asp, cache_isis_env, cache_asap_env]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup default miniconda
        uses: conda-incubator/setup-miniconda@v2.1.0
      - name: Get ASP from cache
        uses: actions/cache@v2
        with:
          path: "/tmp/sp.tar.bz2"
          key: asp-env-${{ runner.os }}-${{ env.ASP_CACHE_NUMBER }}-${{ hashFiles('asap.yml') }}
      - name: Extract ASP tarball to tmp
        run: |
          mkdir /tmp/sp
          tar -xf /tmp/sp.tar.bz2 -C /tmp/sp --strip-components 1
          rm /tmp/sp.tar.bz2
          ls /tmp/sp
      - name: Get ISIS Conda environment from cache
        uses: actions/cache@v2
        with:
          path: "isis-env.tar.gz"
          key: isis-env-${{ runner.os }}-${{ env.ISIS_CACHE_NUMBER }}-${{ hashFiles('isis.yml') }}
      - name: Unpack ISIS Conda environment
        run: |
          mkdir -p $CONDA/envs/isis_for_asp
          tar -xvf isis-env.tar.gz -C /
          rm isis-env.tar.gz
      - name: Get ASAP Conda environment from cache
        uses: actions/cache@v2
        with:
          path: "asap-env.tar.gz"
          key: asap-env-${{ runner.os }}-${{ env.ASAP_CACHE_NUMBER }}-${{ hashFiles('asap.yml') }}
      - name: Unpack ASAP Conda environment
        run: |
          mkdir -p $CONDA/envs/asap
          tar -xvf asap-env.tar.gz -C /
          rm asap-env.tar.gz
      - name: Check contents of isis env
        run: |
          pwd
          echo $CONDA
          ls -lahtr
          ls $CONDA/
          ls $CONDA/envs/isis_for_asp -lahtr
          ls $CONDA/envs/isis_for_asp/bin -lahtr
      - name: Install asap
        run: |
          conda activate asap
          pip install -e .
      - name: Conda info for asap
        run: |
          conda activate asap
          echo $PATH
          conda env config vars list
          conda info
          conda list
      - name: Check isis shared libraries
        run: |
          conda activate asap
          ldd `which qview`
      - name: Test for asap
        run: |
          conda activate asap
          asap
          asap ctx
          asap hirise
          asap common
      - name: Test readme rendering
        run: |
          conda activate asap
          python -m readme_renderer README.rst


